version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: todo-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: todoapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      - ./seed-data:/seed-data:ro
    networks:
      - todo-network
    command: --auth

  mongo-express:
    image: mongo-express:1.0.2
    container_name: todo-mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    ports:
      - "8081:8081"
    networks:
      - todo-network

  mongodb-backup:
    image: mongo:7.0
    container_name: todo-mongodb-backup
    restart: "no"
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: password123
      MONGO_DB: todoapp
    volumes:
      - ./backups:/backups
      - ./scripts:/scripts:ro
    networks:
      - todo-network
    profiles:
      - backup

networks:
  todo-network:
    driver: bridge
    name: todo-network

volumes:
  mongodb_data:
    driver: local
    name: todo-mongodb-data